# -*- coding: utf-8 -*-
"""perceptron.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ScB_J43jtSWaiTwYWa1JYLc8j4Zj1MGS
"""

import numpy as np
import pandas as pd
from sklearn.utils import shuffle

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
df = pd.read_csv(url, header=None)

df = shuffle(df)
df.head()

X = df.iloc[:, 0:4].values   # sepal length, sepal width, petal length, petal width
y = df.iloc[:, 4].values     # species name

print(X[0:5])
print(y[0:5])

from sklearn.model_selection import train_test_split

train_data, test_data, train_labels, test_labels = train_test_split(X, y, test_size=0.25)

# 1 for setosa, 0 otherwise
train_labels = np.where(train_labels == 'Iris-setosa', 1, 0)
test_labels  = np.where(test_labels  == 'Iris-setosa', 1, 0)

print('Train data:', train_data[0:2])
print('Train labels:', train_labels[0:2])
print('Test data:', test_data[0:2])
print('Test labels:', test_labels[0:2])

from sklearn.linear_model import Perceptron

perceptron = Perceptron(eta0=0.1, max_iter=10)
perceptron.fit(train_data, train_labels)

print('Weights:', perceptron.coef_)
print('Bias:', perceptron.intercept_)

test_preds = perceptron.predict(test_data)
print(test_preds)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(test_preds, test_labels)
print('Accuracy:', round(accuracy, 2) * 100, "%")

sl = float(input("Sepal length: "))
sw = float(input("Sepal width: "))
pl = float(input("Petal length: "))
pw = float(input("Petal width: "))

sample = np.array([[sl, sw, pl, pw]])
pred = perceptron.predict(sample)[0]

print("\nPrediction:", pred)
print("Result:", "Iris-setosa" if pred == 1 else "Not Iris-setosa")